services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  restaurant-service:
    build: ../services/restaurant-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy

  order-service:
    build: ../services/order-service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy

  delivery-service:
    build: ../services/delivery-service
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy

  eta-service:
    build:
      context: ..
      dockerfile: services/eta-service/Dockerfile
    ports:
      - "8084:8084"

